### ISSUE TITLE
long epub file names >50 

### ISSUE THREAD

**Issue by fatmanflying** [versfx/EpubReader#1]
Thanks for the library, usually... it works pretty well. I have several efiles which use identifiers that are longer than 50 characters. This makes the library return a null.

Am I doing something funky, that would make this break? It usually works.
Thanks,
Adam

public string ReadEpubFile(string sPnF)
        {
            Epub book = null;
       
            try
            {
                if (File.Exists(sPnF))
                {
                 
                        book = new Epub(sPnF);
   
                }
            }
            catch (Exception e) 
            {
                throw new Exception(" public string ReadEpubFile( "+sPnF+" ) :: " +e.Source+" :: "+ e.Message);
            }
            if (book != null)
            {
                return book.GetContentAsPlainText();
            }
            else
            {
                return "";
            }
        }

**Comment by versfx** [comment]
Are you sure you are using this library? I am asking this because there is no `GetContentAsPlainText` method declared in the code.

I also just tested opening epub files with 100 characters in the filename and it works without any issues.

**Comment by fatmanflying** [comment]
Let me check my other method. THis method is from a different  package. I apologize for the mix up.

**Comment by versfx** [comment]
Have you checked it?

**Comment by fatmanflying** [comment]
Good morning.

Thanks for checking in. I had been slacking off. I have to go back to your model. It seems to work, it is just overly complicated for my simple application. I wish I could just loop through chapters and get the text. At the moment, I am cleaning my colleague's basic HTML out, which is done for internal references within data sets.

Your model is very detailed, and is appreciated. I have to finish writing a method which wraps your HTML content methods. untags them and concatenates them.

**Comment by versfx** [comment]
Yes, I intentionally didn't include HTML parsing functionality in the library because despite EPUB specification requirement for content to be in XHTML format there are many epub books that don't follow this requirement and include regular HTML and sometimes even invalid HTML markup. Handling these cases can be tricky and may require a decent amount of work.

However you can use any existing library for parsing HTML, for example [HtmlAgilityPack](https://www.nuget.org/packages/HtmlAgilityPack). And then you can do something like this:
```c#
using HtmlAgilityPack;

EpubBook book = EpubReader.ReadBook("Peter Pan.epub");
foreach (EpubChapter chapter in book.Chapters)
{
    HtmlDocument htmlDocument = new HtmlDocument();
    htmlDocument.LoadHtml(chapter.HtmlContent);
    StringBuilder sb = new StringBuilder();
    foreach (HtmlNode node in htmlDocument.DocumentNode.SelectNodes("//text()"))
    {
        sb.AppendLine(node.InnerText.Trim());
    }
    string chapterText = sb.ToString();
}
```

Of course if you have nested chapters (chapters including sub-chapters including subchapters...) you will need to iterate chapters recursively.

**Comment by fatmanflying** [comment]
Thank you.

This is to parse large engineering data files. The brainchild of a
university project long gone. However, there are thousands of these files.

I got most of a loop working for your code. It seemed to handle the hidden
landmine zip system that they used. Which I think is what is blowing up the
other reader code.

Thank you for the Agility pack tip.

Adam

**Comment by versfx** [comment]
Glad to hear.

Please let me know if you find any parsing issues with some of the files.
