### ISSUE TITLE
Get Plain Text of Chapter?

### ISSUE THREAD

**Issue by dgerding** [versfx/EpubReader#2]
Hi,
I couldn't figure out how to email so I hope you'll forgive the question here. I've been trying to get the plain text of each chapter from epubs using your library. I've been "foreaching" through the chapters and then using chapter id values (current and next) to find ranges of relevant elements for each chapter but keep getting stuck in the particulars of trimming html.

If you can think of a way to do this or there is already some function that might achieve that result would you be willing to message me or respond here?

Happy to make a small contribution to your favorite charity or paypal account for your time.

Thanks,
Dave Gerding

**Comment by versfx** [comment]
You will need some additional library to extract plain text from HTML. I might recommend using [HtmlAgilityPack](https://www.nuget.org/packages/HtmlAgilityPack) to do that. The reason I didn't add this functionality into the library is that there are many options to do conversion from HTML to plain text and different people may prefer different libraries.

I've added an example of the code that iterates through all the chapters and extracts their content as plain text using HtmlAgilityPack. You can look at the code [here](https://github.com/versfx/EpubReader/tree/master/Source/EpubReaderExamples/ExtractPlainText.cs) or you can just run EpubReaderExamples project from the solution.

**Comment by dgerding** [comment]
Wow, so generous of you to take the time to write that up.  I had been using HtmlAgilityPack - but had failed in my efforts.


I meant it about a favorite charity or your own "Friday beer" fund :)  Send me a paypal destination and I'll send something along.

Thanks again,

Dave Gerding


________________________________

**Comment by versfx** [comment]
Well, this question become very popular so I decided that it is time to create an example.

I don't have a Paypal account (Paypal requires Russian citizens go through their bureaucratic hell in order to receive money, especially from people outside Russia). And besides I have a decent income from my day job, so that's OK.
