### ISSUE TITLE
Incorrect EPUB manifest exception

### ISSUE THREAD

**Issue by andreabertolotto** [versfx/EpubReader#6]
Loading EPUB produced (converted from AZW3) using Calibre 3.3, I get following exception:

Unmanaged exception: System.AggregateException: There were one of more errors. ---> System.Exception: Incorrect EPUB manifest: item with href = "My%20converted%20epub%20from%20Calibre_split_001.html" is missing.
   in VersFx.Formats.Text.Epub.Readers.ChapterReader.GetChapters(EpubBookRef bookRef, List`1 navigationPoints)
   in VersFx.Formats.Text.Epub.Readers.ChapterReader.GetChapters(EpubBookRef bookRef)
   in VersFx.Formats.Text.Epub.EpubBookRef.<GetChaptersAsync>b__33_0()
   in System.Threading.Tasks.Task`1.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()
   in VersFx.Formats.Text.Epub.EpubReader.ReadBook(String filePath)

This is related to href as URL Encoded (look at those "%20"), while Content.Html has decoded fileNames.

I simply added a:
contentFileName = Uri.UnescapeDataString(contentFileName);
after "if", inside VersFx.Formats.Text.Epub\Readers\ChapterReader.cs.

This solved my issue!

**Comment by versfx** [comment]
You are right. Missed that in EPUB specification.

**Comment by versfx** [comment]
This should resolve the issue.
